#!/bin/bash
# This script installs Nginx on an Ubuntu machine and configures it to meet the requirements.

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
