#!/usr/bin/env bash
# This script configures Nginx for a 301 from /redirect_me to another page.

# Update package list
apt-get update

# Install Nginx with -y option to avoid interactive prompt
apt-get -y install nginx

# Allow Nginx HTTP traffic through UFW
ufw allow 'Nginx HTTP'

# Create directory and set permissions
mkdir -p /var/www/html/
chmod -R 755 /var/www

# Create a custom index.html file
echo 'Hello World!' > /var/www/html/index.html

# Configure Nginx
SERVER_CONFIG="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        rewrite ^ https://sketchfab.com/bluepeno/models permanent;
    }
}"

echo "$SERVER_CONFIG" > /etc/nginx/sites-enabled/default

# Restart Nginx (without using systemctl)
if [ "$(pgrep -c nginx)" -le 0 ]; then
    service nginx start
else
    service nginx restart
fi

