#!/usr/bin/env bash
# This script configures Nginx for a custom 404 page.

# Update package list
sudo apt-get update

# Install Nginx with -y option to avoid interactive prompt
sudo apt-get -y install nginx

# Allow Nginx HTTP traffic through UFW
sudo ufw allow 'Nginx HTTP'

# Set permissions for /var/www
chmod -R 755 /var/www

# Create a custom index.html file
echo 'Hello World' > /var/www/html/index.html

# Create a custom 404.html file
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx
NEW_CONFIG="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location  /404.html {
        internal;
        root /var/www/html;
    }

    location ~ /redirect_me {
        rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}"

echo "$NEW_CONFIG" > /etc/nginx/sites-available/default

# Create a symbolic link to enable the configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx (without using systemctl)
if [ "$(pgrep nginx)" -le 0 ]; then
    service nginx start
else
    service nginx restart
fi
