#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Check Nginx status
sudo service nginx status > /dev/null 2>&1

# If Nginx is not running, start it
if [ $? -ne 0 ]; then
    sudo service nginx start
fi

# Configure Nginx to listen on port 80 for all active IPv4 IPs
sudo sed -i '/listen 80 default_server;/a listen 80;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
