#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

# Install Nginx if not already installed
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
