#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process using kill.

# Find the process ID (PID) of the 4-to_infinity_and_beyond script.

kill "$(pgrep -f 4-to_infinity_and_beyond)"
