#!/usr/bin/env bash
# This script displays the time in a 12-hour format with hours from 0 to 12 and minutes from 1 to 59.

hour=0

while [ $hour -le 12 ]; do
  echo "Hour: $hour"
  for minute in {1..59}; do
    echo "$minute"
  done
  ((hour++))
done

