#!/usr/bin/env bash

# Change the DNS resolution for localhost
echo "127.0.0.2 localhost" | sudo tee /etc/hosts

# Change the DNS resolution for facebook.com
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

